/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface SukusAmbulanceWlList {
    }
}
declare global {
    interface HTMLSukusAmbulanceWlListElement extends Components.SukusAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLSukusAmbulanceWlListElement: {
        prototype: HTMLSukusAmbulanceWlListElement;
        new (): HTMLSukusAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "sukus-ambulance-wl-list": HTMLSukusAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface SukusAmbulanceWlList {
    }
    interface IntrinsicElements {
        "sukus-ambulance-wl-list": SukusAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "sukus-ambulance-wl-list": LocalJSX.IntrinsicElements["sukus-ambulance-wl-list"] & JSXBase.HTMLAttributes<HTMLSukusAmbulanceWlListElement>;
        }
    }
}
